export const techStack = [
  { name: "Flutter", icon: "/skill%20logos/flutter.png" },
  { name: "Node.js", icon: "/skill%20logos/nodejs.svg" },
  { name: "Firebase", icon: "/skill%20logos/firebase.png" },
  { name: "MongoDB", icon: "/skill%20logos/mongo.svg" },
  { name: "MySQL", icon: "/skill%20logos/Mysql_logo.png" },
  { name: "DigitalOcean", icon: "/skill%20logos/digitalocean.png" },
  { name: "AWS", icon: "/skill%20logos/aws.png" },
  { name: "Express.js", icon: "/skill%20logos/expressjs.png" },
  { name: "Git VCS", icon: "/skill%20logos/git.png" },
  { name: "GitHub", icon: "/skill%20logos/github.png" },
  { name: "HTML5", icon: "/skill%20logos/html5.png" },
  { name: "Bootstrap", icon: "/skill%20logos/bootstrap.png" },
  { name: "PostgreSQL", icon: "/skill%20logos/Postgresql.png" },
  { name: "JavaScript", icon: "/skill%20logos/javascript.png" },
  { name: "PHP", icon: "/skill%20logos/php.svg" },
  { name: "Python", icon: "/skill%20logos/python.png" },
  { name: "C++", icon: "/skill%20logos/cpp.png" },
  { name: "Selenium", icon: "/skill%20logos/selenium.png" },
  { name: "FastAPI", icon: "/skill%20logos/fastapi.svg" },
  { name: "Flask", icon: "/skill%20logos/flask.webp" },
  { name: "Next.js", icon: "/skill%20logos/nextjs.png" },
  { name: "React.js", icon: "/skill%20logos/react.svg" },
  { name: "TypeScript", icon: "/skill%20logos/typescript.svg" },
  { name: "Tailwind CSS", icon: "/skill%20logos/tailwindcss.png" },
  { name: "Matlab", icon: "/skill%20logos/matlab.svg" },
];
